name: dvault
version: 3.0.0
publish_to: https://onepub.dev/api/jbbxpsdavu/
description: An encrypted key store
environment: 
  sdk: '>=3.7.0 <4.0.0'
dependencies: 
  archive: ^4.0.7
  args: ^2.0.0
  async: ^2.11.0
  dcli: ^7.0.3
  dcli_core: ^7.0.2
  encrypt: ^5.0.1
  meta: ^1.0.0
  path: ^1.0.0
  pointycastle: ^3.0.0
dev_dependencies: 
  lint_hard: ^6.1.1
  test: ^1.24.9
executables: 
  dvault: 
